name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Build (sanity)
        run: go build ./...

      - name: Generate release notes
        id: notes
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "prev=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "## Changes" > RELEASE_NOTES.md
          if [ -n "$PREV_TAG" ]; then
            git log --pretty=format:'- %s (%h)' $PREV_TAG..HEAD >> RELEASE_NOTES.md
          else
            git log --pretty=format:'- %s (%h)' >> RELEASE_NOTES.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
